name: notes_project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

   #Local packages
  encrypt: ^5.0.1
  permission_handler: ^10.2.0
  path_provider: ^2.0.14
  string_validator: ^1.0.0
  cached_network_image: ^3.2.3
  email_validator: ^2.1.17
  shared_preferences: ^2.0.20

  #Features 
  image_picker: ^0.8.6+4
  image_cropper: ^3.0.3
  internet_connectivity_checker: ^1.0.0
  intl: ^0.17.0
  timeago: ^3.3.0
  file_picker: ^5.2.10
  flutter_animate: ^4.1.1+1
  flutter_hooks: ^0.18.6
  path: ^1.8.2
  
  #For share notes
  share_plus: ^6.3.2
  
  #state managment
  flutter_riverpod: ^2.3.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

  #rich text editor 
  flutter_quill: ^7.1.14
  flutter_quill_extensions: ^0.3.1
  tuple: ^2.0.1

  #DB packages
  hydrated_bloc: ^9.1.0
  sqflite: ^2.2.7

  #API packages
  google_sign_in: ^6.0.2
  http: ^0.13.5
  url_launcher: ^6.1.10

  #Test packages
  dio: ^5.1.1  
  mockito: ^5.4.0 
  bloc_test: ^9.1.1
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
      - assets/images/circle-avatar.png
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
