name: notes_project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

   #Local packages
  crypto: ^3.0.2
  shared_preferences: ^2.0.20
  image_picker: ^0.8.6+4
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  email_validator: ^2.1.17
  flutter_animate: ^4.1.1+1
  custom_navigation_bar: ^0.8.2 

  #state managment
  flutter_riverpod: ^2.3.2

  #rich text editor 
  flutter_quill: ^6.4.4

  #DB packages
  google_sign_in: ^6.0.2
  cloud_firestore: ^4.5.0
  firebase_auth: ^4.2.2
  firebase_storage: ^11.1.0
  firebase_core: ^2.9.0

  #API packages
  http: ^0.13.5

  #test db packages
  firebase_auth_mocks: ^0.11.0
  fake_cloud_firestore: ^2.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
      - assets/images/circle-avatar.png
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
